# Generated by Django 5.0.6 on 2024-07-08 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateBond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bond_id', models.CharField(max_length=50)),
                ('counterparty', models.CharField(choices=[('bayport', 'Bayport'), ('reiz', 'REIZ'), ('ifc', 'IFC')], max_length=50)),
                ('start_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(choices=[('ZMW', 'ZMW'), ('USD', 'USD')], default='ZMW', max_length=3)),
                ('interest_rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('bond_rating', models.CharField(choices=[('Aaa', 'Aaa'), ('Aa', 'Aa'), ('A', 'A'), ('Baa', 'Baa'), ('Ba', 'Ba'), ('B', 'B'), ('Caa-C', 'Caa-C')], max_length=50)),
                ('counterparty_type', models.CharField(default='Corporate', editable=False, max_length=50)),
                ('manager', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FixedTermDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fxd_id', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(choices=[('zmw', 'ZMW'), ('usd', 'USD')], max_length=3)),
                ('interest_rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('bond_rating', models.CharField(choices=[('Aaa', 'Aaa'), ('Aa', 'Aa'), ('A', 'A'), ('Baa', 'Baa'), ('Ba', 'Ba'), ('B', 'B'), ('Caa-C', 'Caa-C')], max_length=50)),
                ('counterparty', models.CharField(choices=[('boz', 'BOZ'), ('absa', 'ABSA'), ('fnb', 'FNB'), ('zanaco', 'ZANACO'), ('napsa', 'NAPSA')], max_length=50)),
                ('counterparty_type', models.CharField(default='Corporate', editable=False, max_length=50)),
                ('manager', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GovernmentBondPrimary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bond_id', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('maturity_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='ZMW', max_length=3)),
                ('coupon_rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('bond_rating', models.CharField(choices=[('Aaa', 'Aaa'), ('Aa', 'Aa'), ('A', 'A'), ('Baa', 'Baa'), ('Ba', 'Ba'), ('B', 'B'), ('Caa-C', 'Caa-C')], max_length=50)),
                ('counterparty', models.CharField(choices=[('boz', 'BOZ'), ('absa', 'ABSA'), ('fnb', 'FNB'), ('zanaco', 'ZANACO'), ('napsa', 'NAPSA')], max_length=50)),
                ('counterparty_type', models.CharField(default='Sovereign', editable=False, max_length=50)),
                ('manager', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CouponPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateField()),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque')], max_length=50)),
                ('receipting_manager', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bond_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.governmentbondprimary')),
            ],
        ),
        migrations.CreateModel(
            name='TreasuryBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_bill_id', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('maturity_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='ZMW', max_length=3)),
                ('t_bill_rating', models.CharField(choices=[('Aaa', 'Aaa'), ('Aa', 'Aa'), ('A', 'A'), ('Baa', 'Baa'), ('Ba', 'Ba'), ('B', 'B'), ('Caa-C', 'Caa-C')], max_length=50)),
                ('counterparty', models.CharField(choices=[('boz', 'BOZ'), ('absa', 'ABSA'), ('fnb', 'FNB'), ('zanaco', 'ZANACO'), ('napsa', 'NAPSA')], max_length=50)),
                ('counterparty_type', models.CharField(default='Sovereign', editable=False, max_length=50)),
                ('manager', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
