# Generated by Django 5.0.6 on 2024-07-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixedtermdeposit',
            old_name='bond_rating',
            new_name='bank_rating',
        ),
        migrations.AlterField(
            model_name='fixedtermdeposit',
            name='counterparty',
            field=models.CharField(choices=[('ab_bank', 'AB Bank'), ('absa', 'ABSA'), ('access_bank', 'Access Bank'), ('atlas_mara', 'Atlas Mara'), ('ecobank', 'Ecobank'), ('efc', 'EFC'), ('first_alliance', 'First Alliance'), ('fmc', 'FMC'), ('fnb', 'FNB'), ('indo', 'Indo Zambia Bank'), ('izwe', 'IZWE'), ('lion_finance', 'Lion Finance'), ('lolc', 'LOLC'), ('mfz', 'MFZ'), ('stanbic', 'Stanbic Bank'), ('zanaco', 'ZANACO')], max_length=50),
        ),
    ]
