# Generated by Django 5.0.6 on 2024-07-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_rename_bond_rating_fixedtermdeposit_bank_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentbondprimary',
            name='bond_rating',
            field=models.CharField(choices=[('Aaa', 'Aaa'), ('Aa', 'Aa'), ('A', 'A'), ('Baa', 'Baa'), ('Ba', 'Ba'), ('B', 'B'), ('Caa-C', 'Caa-C')], default='Caa-C', max_length=50),
        ),
        migrations.AlterField(
            model_name='treasurybill',
            name='counterparty',
            field=models.CharField(choices=[('absa', 'ABSA'), ('fnb', 'FNB'), ('zanaco', 'ZANACO'), ('napsa', 'NAPSA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='treasurybill',
            name='t_bill_rating',
            field=models.CharField(choices=[('Aaa', 'Aaa'), ('Aa', 'Aa'), ('A', 'A'), ('Baa', 'Baa'), ('Ba', 'Ba'), ('B', 'B'), ('Caa-C', 'Caa-C')], default='Caa-C', max_length=50),
        ),
    ]
