# Generated by Django 5.0.6 on 2024-07-10 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_alter_corporatebond_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentbondprimary',
            name='currency',
            field=models.CharField(choices=[('zmw', 'ZMW'), ('usd', 'USD')], default='zmw', max_length=3),
        ),
        migrations.AlterField(
            model_name='treasurybill',
            name='currency',
            field=models.CharField(choices=[('zmw', 'ZMW'), ('usd', 'USD')], default='zmw', max_length=3),
        ),
    ]
